meta_product_name: "Pamper Me"
meta_title: "Pmaper Me - Look and feel the best you, anywhere"
meta_description: "The premier service for finding beauty, health, and wellness providers in your area. Connect, book, and enjoy!"
meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
